version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: investigacion_marina_bd
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  springboot-app:
    image: investigacion_marina:latest
    container_name: investigacion_marina_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/investigacion_marina_bd
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
